# Generated by Django 6.0.2 on 2026-02-03 22:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('REPARACION', 'En reparación')], default='ACTIVO', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop')], max_length=20)),
                ('nombre_equipo', models.CharField(max_length=150)),
                ('antivirus', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('service_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=150)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(max_length=50)),
                ('tipo_dd', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVME', 'NVMe')], max_length=20)),
                ('capacidad_dd', models.CharField(max_length=50)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('office_version', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_licencia_office', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_office', models.EmailField(blank=True, max_length=254, null=True)),
                ('monitor', models.BooleanField(default=False)),
                ('service_tag_monitor', models.CharField(blank=True, max_length=100, null=True)),
                ('nobreak', models.BooleanField(default=False)),
                ('perifericos', models.TextField(blank=True, null=True)),
                ('vale_resguardo', models.CharField(blank=True, max_length=100, null=True)),
                ('renovacion', models.CharField(blank=True, max_length=50, null=True)),
                ('resguardo_pdf_generado', models.FileField(blank=True, null=True, upload_to='resguardos/generados/')),
                ('resguardo_pdf_firmado', models.FileField(blank=True, null=True, upload_to='resguardos/firmados/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('REPARACION', 'En reparación')], default='ACTIVO', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=50, unique=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
