# Generated by Django 6.0.2 on 2026-02-05 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_empresa_activo_empresa_contacto_empresa_rfc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('rfc', models.CharField(max_length=13)),
                ('curp', models.CharField(max_length=18)),
                ('clase', models.CharField(choices=[('EBU', 'EBU'), ('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=20)),
                ('departamento', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=150)),
                ('aprobador_gastos', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='inventario.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
