# Generated by Django 6.0.2 on 2026-02-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celular', to='inventario.empleado'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computadora', to='inventario.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
