# Generated by Django 6.0.2 on 2026-02-09 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_celular_empleado_computadora_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('COMPUTADORA', 'Computadora'), ('CELULAR', 'Celular')], max_length=20)),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.CharField(help_text='Nombre de quien autorizó la asignación o devolución', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('celular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.celular')),
                ('computadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.computadora')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_asignaciones', to='inventario.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_asignaciones', to='inventario.empresa')),
            ],
            options={
                'verbose_name': 'Historial de asignación',
                'verbose_name_plural': 'Historial de asignaciones',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
