# Generated by Django 6.0.2 on 2026-02-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_historialasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estatus_equipo',
            field=models.CharField(choices=[('SIN_EQUIPO', 'Sin equipo'), ('CON_EQUIPO', 'Con equipo')], default='SIN_EQUIPO', max_length=20),
        ),
    ]
